import Mathlib
import RequestProject.AdditiveEnergy
import RequestProject.Definitions
import RequestProject.ExplicitCounting
import RequestProject.ShortInterval
import RequestProject.EnergyUpperBound
import RequestProject.MissedSetTransport
import RequestProject.ResearchLadder
import RequestProject.KappaFactory
import RequestProject.DifferenceSieve
import RequestProject.ConcreteConstants
import RequestProject.TaoGafniApproach
import RequestProject.MontgomeryBridge
import RequestProject.GapCloser
import RequestProject.MeasureIdentification
import RequestProject.Blueprint12
import RequestProject.DiagonalDecorrelation
import RequestProject.CrossFormFactor
import RequestProject.BridgeToDIR
import RequestProject.Branch11049
import RequestProject.Branch10677
import RequestProject.DiagonalSuppression
import RequestProject.MainTheorem
import RequestProject.CrossFormFactorPositivity
import RequestProject.MeasureIdentification11049
import RequestProject.MeasureIdentification10677
import RequestProject.BridgeToDIR11049
import RequestProject.BridgeToDIR10677
import RequestProject.EnergyCeiling11049
import RequestProject.EnergyCeiling10677
import RequestProject.DIRMajorantTransfer
import RequestProject.ReproducingKernelExtremal
import RequestProject.MinorArc
import RequestProject.Goldbach
import RequestProject.BHPShortInterval

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false
